<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-V4K2H45Q" name="TestNG Retry" tests="2" failures="1" timestamp="29 Apr 2019 15:17:19 GMT" time="0.064" errors="0">
  <testcase name="fail" time="0.02" classname="TestNGRetryer.TestFail">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestNGRetryer.TestFail.fail(TestFail.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- fail -->
  <testcase name="pass" time="0.003" classname="TestNGRetryer.TestPass"/>
</testsuite> <!-- TestNG Retry -->
